---
title: "cw2"
author: "Maidi"
date: "08/12/2021"
output: html_document
---

```{r}
library(tidyverse)
library(tmap)
library(geojsonio)
library(plotly)
library(rgdal)
library(broom)
library(mapview)
library(crosstalk)
library(sf)
library(sp)
library(spdep)
library(car)
library(fs)
library(janitor)
```


```{r}
LonwardData <- read_csv(here::here("london-ward-well-being-data.csv"), 
                               col_names = TRUE, 
                               locale = locale(encoding = 'Latin1'))
```


```{r}
position <- c(1:11)
Regressiondata<- LonwardData%>%
  clean_names()%>%
dplyr::select(position)

model <- lm(life_expectancy~ .-gcse_point_scores -unauthorised_absence_in_all_schools_percent -public_transport_accessibility-subjective_well_being_average_score,  data = Regressiondata)

#show the summary of those outputs
tidy(model)
```

```{r}
glance(model)
```
```{r}
vif(model)
```

```{r}
summary(model)
```
```{r}
symbox(~childhood_obesity, 
       Regressiondata, 
       na.rm=T,
       powers=seq(-3,3,by=.5))
```

```{r}
symbox(~incapacity_benefit_rate, 
       Regressiondata, 
       na.rm=T,
       powers=seq(-3,3,by=.5))
```
```{r}
symbox(~unemployment_rate, 
       Regressiondata, 
       na.rm=T,
       powers=seq(-3,3,by=.5))
```
```{r}
symbox(~crime_rate, 
       Regressiondata, 
       na.rm=T,
       powers=seq(-3,3,by=.5))
```
```{r}
symbox(~deliberate_fires, 
       Regressiondata, 
       na.rm=T,
       powers=seq(-3,3,by=.5))
```
```{r}
symbox(~homes_with_access_to_open_space_nature_and_percent_greenspace, 
       Regressiondata, 
       na.rm=T,
       powers=seq(-3,3,by=.5))
```


```{r}
par(mfrow=c(2,2))   
plot(model)
```
```{r}
Regressiondata_drop<- Regressiondata[-c(613,67),]%>%
  clean_names()
model_drop <- lm(life_expectancy~ .-gcse_point_scores -unauthorised_absence_in_all_schools_percent -public_transport_accessibility-subjective_well_being_average_score -incapacity_benefit_rate -crime_rate +sqrt(incapacity_benefit_rate)  +log(crime_rate),  data = Regressiondata_drop)

glance(model_drop)
```
```{r}
summary(model_drop)
```

```{r}
model2 <- lm(life_expectancy~ . -childhood_obesity -crime_rate -gcse_point_scores -homes_with_access_to_open_space_nature_and_percent_greenspace -subjective_well_being_average_score -public_transport_accessibility, data = Regressiondata)

tidy(model2)
```

```{r}
glance(model2)
```

```{r}
summary(model2)
```

```{r}
vif(model2)
```

```{r}
symbox(~homes_with_access_to_open_space_nature_and_percent_greenspace, 
       Regressiondata, 
       na.rm=T,
       powers=seq(-3,3,by=.5))
```
```{r}
par(mfrow=c(2,2))   
plot(model2)
```
```{r}
Regressiondata_drop<- Regressiondata[-c(367,613,67),]%>%
  clean_names()

```
```{r}
model3 <- lm(life_expectancy~ . -childhood_obesity -crime_rate -gcse_point_scores -homes_with_access_to_open_space_nature_and_percent_greenspace -subjective_well_being_average_score -public_transport_accessibility, data = Regressiondata_drop)

tidy(model3)
```
```{r}
summary(model3)
```
```{r}
glance(model3)
```

```{r}
par(mfrow=c(2,2))   
plot(model3)
```

```{r}
model2 <- lm(life_expectancy~ . -childhood_obesity -unauthorised_absence_in_all_schools_percent, data = Regressiondata)

tidy(model2)
```

